changing volume reference to absolute link due to this problem:
drewbookpro:atlassian andrewkhoury$ pwd
/data/repos/atlassian
drewbookpro:atlassian andrewkhoury$ docker-compose up -d
Creating atlassian_database_1
ERROR: create atlassian-bamboo/setup-bamboo-db.sh: volume name invalid: "atlassian-bamboo/setup-bamboo-db.sh" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed

This change expects your code to live in /atlassian so use something like `sudo ln -s /data/repos/atlassian /atlassian` to create a symlink to your project.